services:
  - type: web
    name: loteria-backend
    env: node
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false  # Set manually in Render dashboard
      - key: MONGODB_DB
        value: loteria
      - key: NEXTAUTH_SECRET
        sync: false  # Set manually in Render dashboard
      - key: IMAGINE_ART_API_KEY
        sync: false  # Set manually in Render dashboard
